---
title: "Creature Level Analysis"
output: html_document
---

# Data

The GBM of Furrycat's data shows a strong relationship between creature level and, well, nearly everything.

The following formula comes from [this]( https://docs.google.com/spreadsheets/d/1h7qUFcX96VSNL1_WhZGf6rPJNBb53S0SCZBNzpITneU/edit#gid=597001656) Google Doc.


## cerestan's formula

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Multipliers
HAM   = 0.73 / 1000
ARMOR = 10
DPS   = 0.099

KIN_POS   = 0.12
ENG_POS   = 0.1
BLAST_POS = 0.02
HEAT_POS  = 0.02
COLD_POS  = 0.02
ELEC_POS  = 0.02
ACID_POS  = 0.02
STUN_POS  = 0.02

KIN_NEG   = 0.2
ENG_NEG   = 0.11
BLAST_NEG = 0.04
HEAT_NEG  = 0.1
COLD_NEG  = 0.12
ELEC_NEG  = 0.04
ACID_NEG  = 0.02
STUN_NEG  = 0.02

resist_contribution <- function(res, pos_multiplier, neg_multiplier) {
  if (res > 0) {
    return(res * pos_multiplier)
  }
  else if (res < -50) {
    return(-50 * neg_multiplier)
  }
  else {
    return(res * neg_multiplier)
  }
}


creature_level <- function(data) {
  health      = data$health
  action      = data$action
  mind        = data$mind
  armor       = data$armor
  damage_low  = data$damage_low
  damage_high = data$damage_high 
  to_hit      = data$to_hit
  speed       = data$to_hit
  kin         = data$kinetic
  eng         = data$energy
  blast       = data$blast
  heat        = data$heat
  cold        = data$cold
  electricty  = data$electricity
  acid        = data$acid
  stun        = data$stun
  
  
  # CL contributions
  ham_cl = (health + action + mind) * HAM
  armor_cl = armor * ARMOR
  dps_cl = (DPS * to_hit * damage_low) / speed
  kin_cl = resist_contribution(kin, KIN_POS, KIN_NEG)
  eng_cl = resist_contribution(eng, ENG_POS, ENG_NEG)
  blast_cl = resist_contribution(blast, BLAST_POS, BLAST_NEG)
  heat_cl = resist_contribution(heat, HEAT_POS, HEAT_NEG)
  cold_cl = resist_contribution(cold, COLD_POS, COLD_NEG)
  electricity_cl = resist_contribution(electricty, ELEC_POS, ELEC_NEG)
  acid_cl = resist_contribution(acid, ACID_POS, ACID_NEG)
  stun_cl = resist_contribution(stun, STUN_POS, STUN_NEG)
  
  
  return(
    ham_cl + armor_cl + dps_cl + 
    kin_cl + eng_cl + blast_cl + 
    heat_cl + cold_cl + electricity_cl +
    acid_cl + stun_cl
  )
}
```


```{r message=FALSE, warning=FALSE, include=FALSE}
library(magrittr)
library(dplyr)
library(readr)
library(ggplot2)
library(gbm)

# Some of these are obvious typos -- fix later
bad_data <- c("dta2275t", "r8tfng1v",              # weird hardiness
              "er9nq4et", "38u9raer", "6ko7k4ql",  # weird action/dex
              "6td1segp", "6f9lmdbu",              # bad speed
              "frfksnne",                          # Maybe bad to-hit but interesting...
              "kjvtv7d7",                          # has fortitude < 500 AND light armor?
              "4231uemm",                          # trash mob in piket skin (min cl 25) that throws off CL calculations
              "at8d24tc",                          # rancor skin (min cl 35) also throwing off cl calculations
              "8mgpmeev",                          # thune skin also throwing off cl
              "v22scdcg",                          # fambaa
              "ceh4m90v",                          # kimogila
              "mm8gn9sj"                           # kimogila
)
creatures <- read_csv("data/clean/furrycat/creatures.csv") %>%
  filter(!serial %in% bad_data)
templates <- read_csv("data/clean/furrycat/templates.csv")
combined_data <- creatures %>% inner_join(templates, by = join_by(template_id == serial), suffix = c("", ".template"))
normalized_df <- combined_data %>%
  mutate_at(
    vars("kinetic",
         "energy", 
         "blast",
         "heat",
         "cold",
         "electricity",
         "acid",
         "stun",
         "kinetic.effective",
         "kinetic.special",
         "energy.effective",
         "energy.special",
         "blast.effective",
         "blast.special",
         "heat.effective",
         "heat.special",
         "cold.effective",
         "cold.special",
         "electricity.effective",
         "electricity.special",
         "acid.effective",
         "acid.special",
         "stun.effective",
         "stun.special"),
    ~ ifelse(is.na(.), 0, .)
  )

experiments <- read_csv("data/clean/furrycat/experiments.csv")
samples <- read_csv("data/clean/furrycat/samples.csv")
```

Let's see how this model performs on the furrycat data set.


```{r echo=FALSE, message=FALSE, warning=FALSE}
normalized_df <- normalized_df %>%
  rowwise() %>%
  mutate(predicted_level = creature_level(cur_data())) %>%
  ungroup()

ggplot(normalized_df, aes(x = predicted_level, y = level)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  theme_minimal() +
  ggtitle("Actual vs Predicted Creature Levels")

```



