---
title: "Fixing Bio-Engineer"
output: html_document
---

# Introduction

The Massively Multiplayer Online Game, Star Wars: Galaxies was released over 20 years ago. The game was shut down on December 15, 2011; but from at least late-2006, an on-going emulation project has been attempting to recreate the game.

One of the most interesting and complex systems in SWG was the Bio-Engineering profession. This is an attempt to reverse-engineer it from historical data.

# Data

All data is scraped from Furrycat's archives. The raw data has been archived to this git repository, and scripts to construct CSVs and import in R as dataframes are provided in the `scripts/` folder.

# Assumptions

1. The real game logic is probably rounded to human-friendly whole numbers. For example, linear regression may indicate values such as 14.995 -- here we'll round this up to 15, assuming that it's unlikely that game developers were tuning parameters to that level.
2. The real game logic was certainly efficient on C++ 98 running on hardware from 2003. It was unlikely to be very sophisticated or computationally expensive.

# Attribute Analysis

- [Health Analysis](health_analysis.html)
- [Action Analysis](action_analysis.html)
- [Mind Analysis](mind_analysis.html)
- [Speed Analysis](speed_analysis.html)
- [To-Hit Analysis](to_hit_analysis.html)
- [Damage Analysis](damage_analysis.html)
- [Armor Analysis](armor_analysis.html)
- To Do - [Resists Analysis](resists_analysis.html)
- Work In Progress - [Creature Level Analysis](creature_level_analysis.html)
