---
title: "To-Hit Analysis"
output: html_document
---
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("R/data.R")
library(mgcv)
library(broom)
library(ggplot2)
```
# Data

The GAM of Furrycat's data shows a strong relationship between to-hit and cleverness

```{r echo=TRUE, message=FALSE, warning=FALSE}
model <- gam(
  formula = to_hit ~
    s(hardiness) +
    s(fortitude) + 
    s(dexterity) + 
    s(endurance) +
    s(intellect) + 
    s(cleverness) + 
    s(courage) + 
    s(dependability) +
    s(power) +
    s(fierceness) +
    armor,
  family = gaussian(),
  data = normalized_df
)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
summary(model)
```

This is easy to see with the graph.

```{r echo=TRUE, message=FALSE, warning=FALSE}
ggplot(normalized_df, aes(x = cleverness, y = to_hit)) +
  geom_point() +
  ggtitle("Cleverness vs To-Hit")
```

And the GAM shows linear relationships.

```{r echo=TRUE, message=FALSE, warning=FALSE}
plot(model, select = 6)
```

The linear model shows high correlation and low residuals.

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=TRUE}
model <- lm(to_hit ~ cleverness, data = normalized_df)
summary(model)
```

And looks like this.

```{r echo=FALSE, message=FALSE, warning=FALSE}
normalized_df$predicted_to_hit <- predict.lm(model, newdata = normalized_df)

ggplot(normalized_df, aes(x = to_hit, y = predicted_to_hit)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  ggtitle("Linear Model Predicted Action vs Actual")

```

# Conclusion

To-Hit is roughly captured by the following formula, $tohit \approx 0.195 + 0.0006455 * cleverness$.
